jobs:
- name: cell_platform_z1
  vm_extensions: [diego-platform-cell-profile]
  instances: 1
  properties:
    diego:
      rep:
        placement_tags: [platform]
  inject: (( inject jobs.cell_z1 ))
