jobs:
- name: cell_platform_z1
  instances: 1
  properties:
    diego:
      rep:
        placement_tags: [platform]
  inject: (( inject jobs.cell_z1 ))
- name: cell_platform_z2
  instances: 1
  properties:
    diego:
      rep:
        placement_tags: [platform]
  inject: (( inject jobs.cell_z2 ))
